// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LoginInvalido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginInvalido', async function() {
    await driver.get("http://s3-group-10-c6-fe.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.css("a:nth-child(2) > .btn_header")).click()
    await driver.findElement(By.css(".container-login")).click()
    await driver.findElement(By.css(".input-login:nth-child(2)")).click()
    await driver.findElement(By.css(".input-login:nth-child(2)")).sendKeys("peter@mail.com")
    await driver.findElement(By.css(".input-login:nth-child(4)")).sendKeys("1234567")
    await driver.findElement(By.css(".btn-login")).click()
    {
      const element = await driver.findElement(By.css(".btn-login"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
