insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Check in: 15hs - Checkout: 11hs', 2, 'Check in', 2, 8);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Check in: 15hs - Checkout: 11hs', 3, 'Check in', 2, 8);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Check in: 14hs - Checkout: 10hs', 4, 'Check in', 1, 8);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Check in: 15hs - Checkout: 11hs', 5, 'Check in', 3, 8);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Check in: 14hs - Checkout: 10hs', 6, 'Check in', 4, 8);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Cancellation withou refound', 7, 'Cancellation', 5, 7);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Cancellation withou refound', 8, 'Cancellation', 6, 7);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Cancellation withou refound', 9, 'Cancellation', 7, 7);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Cancellation withou refound', 10, 'Cancellation', 8, 7);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('24-hour security ', 11, 'Security', 9, 9);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Key card access ', 12, 'Security', 10, 9);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('24-hour security ', 13, 'Security', 11, 9);
insert into `policies` (`description`, `id`, `name`, `product_id`, `type_id`) values ('Key card access ', 14, 'Security', 12, 9);